name: HealthCheck

on:
    push:
        branches:
            - main

jobs:
    health_check:
        runs-on: ubuntu-20.04
        steps:
            - name: check the deployed URL
              uses: jtalk/url-health-check-action@v4
              with:
                url: https://pokedex-aqs0.onrender.com/
                max-attempts: 3
                retry-delay: 20s